name: CI

# Controls when the action will run.
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR: https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: bazel-contrib/setup-bazel@0.15.0

      - name: bazel build
        run: >-
          bazel
          build
          //:sonar_scanner
          //:sonarqube_coverage_generator

      # TODO Building //docs:docs is not working correctly
      # - name: bazel aquery
      #   run: >-
      #     bazel
      #     aquery
      #     ...
